### ISSUE TITLE
Add 6.0 release

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ncurses-feedstock#14]
This would be a breaking release, but we should probably add it at some point. We need to make sure everything is pinned correctly before we do though.

**Comment by flub** [comment]
Isn't a safe way to do this to introduce a ncurses6 package name?  Then dependent packages can migrate slowly and safely.

**Comment by jakirkham** [comment]
I'm not sure how safe it is to mix two versions of `ncurses`. What if symbols loaded from the two libraries clash?

**Comment by jakirkham** [comment]
Addressed by adding 6.1

ref: https://github.com/conda-forge/ncurses-feedstock/pull/40
