### ISSUE TITLE
Error from conda build prefix length?

### ISSUE THREAD

**Issue by wesm** [conda-forge/ncurses-feedstock#20]
started getting this error somewhat recently

```
WARNING:/home/travis/build/wesm/parquet-cpp/miniconda/lib/python2.7/site-packages/conda_build/build.pyc:Build prefix failed with prefix length 255
WARNING:/home/travis/build/wesm/parquet-cpp/miniconda/lib/python2.7/site-packages/conda_build/build.pyc:Error was: 
WARNING:/home/travis/build/wesm/parquet-cpp/miniconda/lib/python2.7/site-packages/conda_build/build.pyc:ERROR: placeholder '/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho' too short in: conda-forge::ncurses-5.9-8
WARNING:/home/travis/build/wesm/parquet-cpp/miniconda/lib/python2.7/site-packages/conda_build/build.pyc:One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING:/home/travis/build/wesm/parquet-cpp/miniconda/lib/python2.7/site-packages/conda_build/build.pyc:Falling back to legacy prefix length of 80 characters.
WARNING:/home/travis/build/wesm/parquet-cpp/miniconda/lib/python2.7/site-packages/conda_build/build.pyc:Your package will not install into prefixes > 80 characters.
updating index in: /home/travis/build/wesm/parquet-cpp/miniconda/conda-bld/linux-64
updating index in: /home/travis/build/wesm/parquet-cpp/miniconda/conda-bld/noarch
```

https://travis-ci.org/wesm/parquet-cpp/jobs/157760286

comes from

https://github.com/apache/parquet-cpp/blob/master/ci/travis_conda_build.sh

What's going on here? I did some google searches but didn't find any quick workarounds.

**Comment by wesm** [comment]
seems a workaround is to install miniconda in /home/travis, let me try that. any other suggestions let me know

**Comment by jakirkham** [comment]
What versions of `conda` and `conda-build` are you using?

**Comment by wesm** [comment]
from the build log

```
Current conda install:
             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 2.0.0
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /home/travis/build/wesm/parquet-cpp/miniconda  (writable)
  default environment : /home/travis/build/wesm/parquet-cpp/miniconda
     envs directories : /home/travis/build/wesm/parquet-cpp/miniconda/envs
        package cache : /home/travis/build/wesm/parquet-cpp/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by jakirkham** [comment]
Thanks.

Sorry am on my phone so can't look at the logs ATM.

Could you please try switching back to `conda-build` series `1.x` and see if it persists? It may be a consequence of the increased prefix length.

**Comment by wesm** [comment]
I was able to work around for now by installing miniconda in a shorter prefix (it was 85 characters -- hence the issue I presume -- now less than 60).

**Comment by brentp** [comment]
we are also seeing this error with conda-build 2.0.0 even though our path length is << 255. I guess once ncurses is re-built with the new prefix length of 255 this will go away?

**Comment by jakirkham** [comment]
Yes, it will go away when we rebuild with `conda-build` version `2`.

This affects a number of packages of which `ncurses` is only one. Please see issue ( https://github.com/conda-forge/conda-forge.github.io/issues/171 ) and continue the discussion there. Going to close this out to consolidate the discussion.

Right now we are blocked upgrading `conda-build` to version `2` until there is a `conda-smithy` release. See issue ( https://github.com/conda-forge/conda-smithy/issues/305 ).
