### ISSUE TITLE
Rebuild with long place-holder

### ISSUE THREAD

**Issue by bgruening** [conda-forge/ncurses-feedstock#24]
Are there any plans to rebuild this package to get the long place-holder?

Thanks!
Bjoern

**Comment by jakirkham** [comment]
We are aware of this issue and are tracking in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/171 ). Going to close this out to consolidate the discussion.

Right now we are blocked until there is a `conda-smithy` release. See issue ( https://github.com/conda-forge/conda-smithy/issues/305 ).

**Comment by jakirkham** [comment]
Also related issue ( https://github.com/conda-forge/ncurses-feedstock/issues/20 ).
