### ISSUE TITLE
TERM=rxvt-unicode* failures with ncurses-5.9

### ISSUE THREAD

**Issue by unode** [conda-forge/ncurses-feedstock#29]
As suggested from #17, I'm opening an issue about it here.
```
% conda --version
conda 4.2.13
...
% conda install ncurses
ncurses                   5.9                          10    conda-forge
...
% clear
terminals database is inaccessible
...
% infocmp 
infocmp: couldn't open terminfo file (null).
...
% env | grep TERM
COLORTERM=rxvt
TERM=rxvt-unicode-256color
```

Any program that relies on `infocmp` to obtain terminal information reports errors or uses a fallback (usually to a dumb terminal).

The `clear` and `infocmp` errors all go away if I disable conda or if I set `TERM=xterm` or `TERM=rxvt`. Any variant starting with `TERM=rxvt-unicode` fails.
This is possibly due to a missing entry in the database matching these `TERM`s.
#14 may help. I have `ncurses 6.0` on the system.

**Comment by jjhelmus** [comment]
> I have ncurses 6.0 on the system

I think this is the root cause of the issue.  Apparently ncurses 6 breaks ABI with ncurses 5, see pypa/manylinux#94.  

Can you provide some more details on the system you are using @Unode so that we can attempt to reproduce this and see if a fix can be created?

**Comment by Unode** [comment]
I'm using [Sabayon Linux](https://www.sabayon.org). Currently on the system I get:

    # ls -l /lib64/libncurses*
    lrwxrwxrwx 1 root root     17 Jun 22  2016 /lib64/libncurses.so.6 -> libncurses.so.6.0*
    -rwxr-xr-x 1 root root 167824 Jun 10  2016 /lib64/libncurses.so.6.0*
    lrwxrwxrwx 1 root root     18 Jun 22  2016 /lib64/libncursesw.so.6 -> libncursesw.so.6.0*
    -rwxr-xr-x 1 root root 254312 Jun 10  2016 /lib64/libncursesw.so.6.0*

I can't reproduce the problem on CentOS 6.5 nor CentOS 7 machines that have ncurses 5.7 and 5.9 respectively.
I don't currently have access to another machine with ncurses 6 installed.

**Comment by jakirkham** [comment]
We are migrating to `ncurses` 6.1. Also we are going to start making use of `DT_RPATH` in the stack. Expect either one of these will resolve this issue. The latter should make it a non-issue if the system has a different `ncurses` version.

ref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/68
