### ISSUE TITLE
libtermcap.so not produced?

### ISSUE THREAD

**Issue by smithsp** [conda-forge/ncurses-feedstock#31]
When installing the linux64 version, I did not get `libtermcap.so`.  Is that expected?  Do you know what switches to change to get that library?

**Comment by smithsp** [comment]
(I had a typo `libncurses` -> `libtermcap`)

**Comment by jakirkham** [comment]
It's true we don't. We produce terminfo (`libtinfow.so`) instead. termcap is the predecessor to terminfo and pretty old. Is there some reason you would want this older termcap library instead of terminfo? Have you tried using terminfo?

xref: http://tldp.org/HOWTO/Text-Terminal-HOWTO-16.html

**Comment by smithsp** [comment]
@jakirkham 
Thanks for your prompt response.
I am on a system that did not have `libtermcap2.so`.  I was able to find online that someone else suggested `libtinfo.so`, and giving a symbolic link named the former to the latter worked.
(Mention @orso82)

**Comment by jakirkham** [comment]
I suppose that is a solution we could codify if needed. Did the build in question not allow the termcap/terminfo library to be specified?

**Comment by smithsp** [comment]
I don't know if the build allowed the library to be specified.  If I go back and address this issue, I will try to add comments here about what worked.
