### ISSUE TITLE
doesn't build with conda-build 2.1.6+

### ISSUE THREAD

**Issue by lexual** [conda-forge/ncurses-feedstock#33]
Appears from conda-build 2.1.6 on, run_test.sh & run_test.py get ran as long as they exist, so the osx specific setting is not succeeding, and causing linux build test to fail.

**Comment by jakirkham** [comment]
Do you have a reference for the build failure? Is it in the CIs?

**Comment by lexual** [comment]
```
conda install conda-build=2.1.5
conda build -t . # pass
conda install conda-build=2.1.9
conda build -t . # fail
```

nothing in CI, can post logs locally if that helps, or simple test case given above.

**Comment by jakirkham** [comment]
Well the CIs are on 2.1.9. So it should be reproducible there. Does it still happen if you are not in the recipe directory?

**Comment by lexual** [comment]
how should I trigger a CI fail?
dummy merge request?

**Comment by lexual** [comment]
hmm, CI build fixed, will have to investigate further locally to see what's going on

**Comment by lexual** [comment]
So travis has build failure, see bottom few lines, same error I was getting locally on linux-64:

https://travis-ci.org/conda-forge/ncurses-feedstock/builds/220169233

**Comment by jakirkham** [comment]
Not sure if this is still an issue, but `ncurses` went to 6.1, the Python tests have been dropped, and we have migrated to `conda-build` 3. Given these rather large changes, going to close. If there is some build issue, let's open a new issue.
