### ISSUE TITLE
Build issues in emacs feedstock 

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/ncurses-feedstock#36]
We're having some build issues in the emacs feedstock on OS X. See https://github.com/conda-forge/emacs-feedstock/pull/16. Master built properly about a month ago (see https://travis-ci.org/conda-forge/emacs-feedstock/builds), but now it fails (https://travis-ci.org/conda-forge/emacs-feedstock/builds/282852138). The error is 

```
  CCLD     temacs
Undefined symbols for architecture x86_64:
  "_tgetent", referenced from:
      _init_tty in term.o
  "_tgetflag", referenced from:
      _init_tty in term.o
  "_tgetnum", referenced from:
      _init_tty in term.o
  "_tgetstr", referenced from:
      _init_tty in term.o
      _term_get_fkeys_1 in term.o
  "_tgoto", referenced from:
      _cmcostinit in cm.o
      _cmgoto in cm.o
  "_tparm", referenced from:
      _tparam in terminfo.o
  "_tputs", referenced from:
      _cmcostinit in cm.o
      _cmgoto in cm.o
      _calccost in cm.o
      _tty_turn_off_insert in term.o
      _string_cost in term.o
      _per_line_cost in term.o
      _tty_clear_to_end in term.o
      ...

```

As far as I understand, those functions come from ncurses, so it seems likely that the issue is some change with the ncurses package. Were there any changes to ncurses in the past month that could have caused this?

**Comment by asmeurer** [comment]
Hmm, from the commit history of this repo, it seems it hasn't changed much recently. So maybe the problem lies somewhere else. Either way, if someone has any ideas, I'd love to hear them.

**Comment by jakirkham** [comment]
Followed up in this [comment]( https://github.com/conda-forge/emacs-feedstock/pull/16#issuecomment-334241528 ). Let's keep the discussion over there unless we figure out some larger issue is at play.

**Comment by jakirkham** [comment]
Closing as it sounds like this got resolved in the `emacs` build.
