### ISSUE TITLE
Linking with -lncurses should also bring in -ltinfo

### ISSUE THREAD

**Issue by jmarshall** [conda-forge/ncurses-feedstock#44]
In the ncurses implementation of Curses, symbols such as `cbreak` are provided by the separate tinfo library. In the old days (prior to [this transition](
https://wiki.ubuntu.com/NattyNarwhal/ToolchainTransition) or with `-flat_namespace` on the macOS linker), just listing `-lncurses` on your linker command line sufficed to bring in both libraries, but nowadays this is no longer the case if packagers do not take steps to arrange it.

In PR #10, you ultimately rejected combining libtinfo into libncurses (fair enough), and suggested that programs using libncurses should also explicitly link with libtinfo, and that providing the correct information via pkg-config suffices.

Requiring Curses-using projects to know about and link with libtinfo is reasonable for projects using autoconf macros (like AX_WITH_CURSES) or pkg-config to choose how to link Curses. It is not reasonable for projects that just have `-lcurses` or so hardcoded in their Makefiles, because if they add `-ltinfo` to their Makefiles they will no longer be portable to Curses implementations that do not have a separate tinfo library. (Note also that autoconf-archive's AX_WITH_CURSES has never implemented anything like this.)

People expect linking with solely `-lncurses` to Just Work, and the Linux distributions have arranged for this post-transition by making _libncurses.so_ actually be a linker script that brings in both libraries. Ideally conda would do so too.

As background: PR #10 was a response to #9, which was distilled from bioconda/bioconda-recipes#1391. That original samtools build failure has been reported again as samtools/samtools#940. The crux of the underlying issue is discussed in https://github.com/samtools/samtools/issues/940#issuecomment-418754819.

Conda can arrange for `-lncurses` by itself to just work by:

1. For the GNU linker (i.e., on Linux), replace the installed _libncurses.so_ with a script saying `INPUT(libncurses.so.6 -ltinfo)` and similarly for the wide versions etc.

    See e.g. 5.7-4.20100116 in the [CentOS RPM's ChangeLog](https://git.centos.org/blob/rpms!ncurses.git/c7/SPECS!ncurses.spec) for their technique.

2. On macOS, use the Darwin linker's re-exporting facilities to make libtinfo.dylib a sub-library of libncurses.dylib. For example, this could be done in your _build.sh_ by patching the generated _ncurses/Makefile_ between the configure and make steps:

```diff
--- ncurses/Makefile.orig
+++ ncurses/Makefile
@@ -129,7 +129,7 @@
 LDFLAGS		=  -Wl,-search_paths_first  
 
 SHLIB_DIRS	= -L../lib
-SHLIB_LIST	= $(SHLIB_DIRS)  -ltinfo
+SHLIB_LIST	= $(SHLIB_DIRS)  -Wl,-reexport-ltinfo
 TINFO_LIST	= $(SHLIB_DIRS) 
 TICS_LIST	= $(SHLIB_DIRS)  -ltinfo
```

This is a more palatable alternative to combining libtinfo into libncurses, but has the same effect.

**Comment by jakirkham** [comment]
So I’m not sure I understand why people’s `Makefile`s are hard coding how they link to `ncurses`? Wouldn’t they be better off using standard build tools like `pkg-config`? What am I missing here?

**Comment by jmarshall** [comment]
You're missing that people who can barely write makefiles have been doing it that way for twenty years. Pop over to bioconda and look at some of the borked upstream makefiles that they're wrapping up. :smile:

Not everyone is in a position to use `pkg-config`. Either because they're not interested in learning it, or because they're producing packages that need to be usable by people who (alas) don't have `pkg-config` themselves.

**Comment by jjhelmus** [comment]
I would be be fine with the proposed method for making `-lncurses` to just work.  The Linux solution seem to be used by all the distribution that I've examined.  @jmarshall would you be interested in submit a PR for this?

**Comment by jmarshall** [comment]
PR is #45, tested on both platforms by manually running `build.sh` from within a _ncurses-6.1_ directory unpacked from the tarball — I don't have all the conda-forge infrastructure installed.

**Comment by Carreau** [comment]
Not completely sure if related but I had an issue with the tmux recipe not finding `libtinfo.so.6`. I manually simlinked, which worked.

**Comment by jakirkham** [comment]
That's probably an issue with `tmux`. Could you please raise an issue on that feedstock with more details?

**Comment by Carreau** [comment]
> That's probably an issue with `tmux`. Could you please raise an issue on that feedstock with more details?

sure.

**Comment by jmarshall** [comment]
Meanwhile — is there anything I should add to facilitate the review of PR #45?
