### ISSUE TITLE
Issue with linux-64/ncurses-6.2-he1b5a44_2

### ISSUE THREAD

**Issue by savingoyal** [conda-forge/ncurses-feedstock#59]
Issue:
I am trying to fetch `linux-64/ncurses` on my macOS machine. My use case is to create a relocatable environment on a mac that I can ship to a linux-64 instance on the cloud.

`CONDA_SUBDIR=linux-64 CONDA_CHANNELS=conda-forge conda create --yes --name ncurses_test ncurses`

The previous version of `ncurses` `6.2-he1b5a44_1` works just fine.
<details>
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/savin/opt/miniconda3/envs/ncurses_test

  added / updated specs:
    - ncurses

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h5dbcf3e_17
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h5dbcf3e_17
  ncurses            conda-forge/linux-64::ncurses-6.2-he1b5a44_2

Preparing transaction: done
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 317, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 346, in handle_txn
        unlink_link_transaction.execute()
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 231, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 591, in _verify
        itervalues(prefix_action_groups)):
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 411, in _verify_individual_level
        error_result = axn.verify()
      File "/Users/savin/opt/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/Users/savin/opt/miniconda3/lib/python3.7/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/savin/opt/miniconda3/pkgs/ncurses-6.2-he1b5a44_2/share/terminfo/N/NCR260VT300WPP'

`$ /Users/savin/opt/miniconda3/bin/conda create --yes --name ncurses_test ncurses`

  environment variables:
                 CIO_TEST=<not set>
           CONDA_CHANNELS=conda-forge
                CONDA_EXE=/Users/savin/opt/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/Users/savin/opt/miniconda3/bin/python
               CONDA_ROOT=/Users/savin/opt/miniconda3
              CONDA_SHLVL=0
             CONDA_SUBDIR=linux-64
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/savin/opt/miniconda3/bin:/Users/savin/opt/miniconda3/bin:/Users
                          /savin/opt/miniconda3/bin:/usr/local/opt/libpq/bin:/Users/savin/Code/g
                          oogle-cloud-sdk/bin:/Users/savin/opt/miniconda3/condabin:/usr/local/bi
                          n:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/savin/.condarc
 populated config files : /Users/savin/.condarc
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.7.9.final.0
       virtual packages : __osx=10.15.6
       base environment : /Users/savin/opt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/savin/opt/miniconda3/pkgs
                          /Users/savin/.conda/pkgs
       envs directories : /Users/savin/opt/miniconda3/envs
                          /Users/savin/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.9 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
</details>

<br/>
Environment (<code>conda list</code>):
<details>

```
$ CONDA_SUBDIR=linux-64 conda list
```
```
# packages in environment at /Users/savin/opt/miniconda3:
#
# Name                    Version                   Build  Channel
astroid                   2.3.3                    pypi_0    pypi
boto3                     1.15.16                  pypi_0    pypi
botocore                  1.18.16                  pypi_0    pypi
brotlipy                  0.7.0           py37haf1e3a3_1000
ca-certificates           2020.10.14                    0
certifi                   2020.6.20                py37_0
cffi                      1.14.3           py37hed5b41f_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                    pypi_0    pypi
conda                     4.8.5                    py37_0
conda-package-handling    1.6.1            py37h1de35cc_0
cryptography              3.1.1            py37hddc9c9b_0
idna                      2.10                       py_0
isort                     4.3.21                   pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
lazy-object-proxy         1.4.3                    pypi_0    pypi
libcxx                    10.0.0                        1
libedit                   3.1.20191231         h1de35cc_1
libffi                    3.3                  hb1e8313_2
mccabe                    0.6.1                    pypi_0    pypi
metaflow                  2.2.3                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1
openssl                   1.1.1h               haf1e3a3_0
pip                       20.2.3                   py37_0
pycosat                   0.6.3            py37h1de35cc_0
pycparser                 2.20                       py_2
pylint                    2.4.4                    pypi_0    pypi
pyopenssl                 19.1.0                     py_1
pysocks                   1.7.1                    py37_0
python                    3.7.9                h26836e1_0
python-dateutil           2.8.1                    pypi_0    pypi
python.app                2                       py37_10
readline                  8.0                  h1de35cc_0
requests                  2.24.0                     py_0
ruamel_yaml               0.15.87          py37haf1e3a3_1
s3transfer                0.3.3                    pypi_0    pypi
setuptools                50.3.0           py37h0dc7051_1
six                       1.15.0                     py_0
sqlite                    3.33.0               hffcf06c_0
tk                        8.6.10               hb0a8c7a_0
tqdm                      4.50.2                     py_0
typed-ast                 1.4.1                    pypi_0    pypi
urllib3                   1.25.10                    py_0
wheel                     0.35.1                     py_0
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.5                h1de35cc_0
yaml                      0.2.5                haf1e3a3_0
zlib                      1.2.11               h1de35cc_3
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ CONDA_SUBDIR=linux-64 CONDA_CHANNELS=conda-forge conda info
```
```

     active environment : None
            shell level : 0
       user config file : /Users/savin/.condarc
 populated config files : /Users/savin/.condarc
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.7.9.final.0
       virtual packages : __osx=10.15.6
       base environment : /Users/savin/opt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/savin/opt/miniconda3/pkgs
                          /Users/savin/.conda/pkgs
       envs directories : /Users/savin/opt/miniconda3/envs
                          /Users/savin/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.9 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by savingoyal** [comment]
This is biting quite a few of our users - https://gitter.im/metaflow_org/community?at=5f84e9b999e1ab4dd1f69086

@fhoehle
@jakirkham
@mingwandroid

**Comment by jakirkham** [comment]
This doesn't seem so much like an `ncurses` issue, but instead a Conda issue feature request. So am going to close this out. Would recommend following up [on the Conda issue tracker]( https://github.com/conda/conda/issues ).

**Comment by fhoehle** [comment]
@savingoyal I would recommend to create the env using docker: `docker run -it condaforge/miniforge3 conda create -n test ncurses -y` which finishes successfully. The created env can packaged using `conda pack` and shipped.

**Comment by mingwandroid** [comment]
You are trying to create a linux conda environment on a case-insensitive filesystem. This is bound to not end well. You can use linux conda envs successfully on macOS though, but you must create a case-sensitive volume on which to mount it.
