### ISSUE TITLE
Undefined symbols on OSX

### ISSUE THREAD

**Issue by cel4** [conda-forge/ncurses-feedstock#9]
conda-forge's version of libncurses does not seem to define all required symbols on OSX. The libncurses library in the `r` channel works like a charm.
```
Undefined symbols for architecture x86_64:
  "_cbreak", referenced from:
      _curses_tv_init in bam_tview_curses.o
  "_keypad", referenced from:
      _curses_tv_init in bam_tview_curses.o
  "_stdscr", referenced from:
      _curses_tv_init in bam_tview_curses.o
      _curses_mvaddch in bam_tview_curses.o
      _curses_attron in bam_tview_curses.o
      _curses_attroff in bam_tview_curses.o
      _curses_clear in bam_tview_curses.o
      _curses_loop in bam_tview_curses.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jakirkham** [comment]
So, this is only telling half the story. Could you please share what you are building that is using `ncurses` and include relevant recipes, build scripts, logs, etc in some gist and link us to that gist?

**Comment by cel4** [comment]
You can find the recipe that triggered the error in this PR: https://github.com/bioconda/bioconda-recipes/pull/1391. I have not included any logs of this recipe because I felt that the problem must be further downstream. I think the interesting part is to understand why `ncurses` in the `r` channel defines those symbols whereas conda-forge's version does not.

Here's conda's build log, anyways. I didn't see any helpful information - maybe you can spot a problem: https://gist.github.com/cel4/3863ae446e296c4ec4a7d0c20a00ed6b

**Comment by jakirkham** [comment]
So, I'm not seeing where `ncurses` is installed for the build step. Also, could you add `conda config --set show_channel_urls true`? It isn't clear to me where some packages are coming from.

**Comment by jakirkham** [comment]
It seems that this is merely an issue of pinning to the right `ncurses` or at least that was what was determined downstream. Going to close this. If more issues come up, please explain what has occurred and then feel free to reopen or ask me to.

**Comment by cel4** [comment]
Sorry for being confusing. This is not about pinning. conda-forge provides version `ncurses-5.9`, and so does the `r` channel. The issue here is that conda-forge's version seems to lack some symbols.

Building the recipe in bioconda environment worked because they do not yet use the conda-forge repository. Once they do, they will see the same issue as I do currently.

To understand why the error occurs you can install `ncurses` from the  `r` channel, and check the installed `libncurses.5.dylib` file by doing `nm libncurses.5.dylib | grep _cbreak`. It should output `0000000000026dd0 T _cbreak` - so the symbol is defined.

If you do the same with conda-forge's version (5.9-5 conda-forge),  `nm libncurses.5.dylib | grep _cbreak` prints: `U _cbreak` telling that `_cbreak` is undefined. That's why the error I posted occurs in the first place.

What's not clear to me is why the two libraries have a different set of defined symbols.

However, as it is now samtools cannot be linked against conda-forge's version of ncurses. This is not because of different version, but rather because of different ways of them being compiled.

**Comment by jakirkham** [comment]
So, I can find `cbreak` and `stdscr`, but they do not have underscores. However, `keypad` is missing from `libncurses`, but is preset in `libtinfo` without the underscore.

**Comment by jakirkham** [comment]
On Mac, all of these symbols are present in `libtinfo` as stated. See below. If you build your package to link against `libtinfo` as well, you should be fine.

```
$ nm /zopt/conda/envs/ncenv/lib/libtinfo.dylib | grep '_cbreak\|_keypad\|_stdscr'
0000000000006a20 T __nc_keypad
0000000000007040 T _cbreak
00000000000069c0 T _keypad
000000000002fbc8 S _stdscr
```

**Comment by jakirkham** [comment]
This is also true of `libtinfow` if you would prefer to have widec support.

```
$ nm /zopt/conda/envs/ncenv/lib/libtinfow.dylib | grep '_cbreak\|_keypad\|_stdscr'
0000000000006a20 T __nc_keypad
0000000000007040 T _cbreak
00000000000069c0 T _keypad
000000000002fbc8 S _stdscr
```

**Comment by jakirkham** [comment]
Please see this PR ( https://github.com/conda-forge/ncurses-feedstock/pull/10 ), which would combine `libtinfo` and `libncurses` together. Keep in mind, this is opposite of the trend that ncurses developers have been pushing so this may not be sustainable in the long term.

**Comment by jakirkham** [comment]
I've also added a less controversial PR ( https://github.com/conda-forge/ncurses-feedstock/pull/11 ), which will make it possible to use `pkg-config` to get the right linking arguments. It will pickup `libtinfo` and `libncurses`.

**Comment by cel4** [comment]
Let's close this one. Having thought about the problem a little bit, I really think that patching the Makefiles is the right way to go here. Thanks for your help in understanding the problem! 👍

**Comment by jbelyeu** [comment]
Still seeing this problem with ncurses 5.9-9. Details available here: https://travis-ci.org/gogetdata/ggd-recipes/jobs/164147746

**Comment by jakirkham** [comment]
Couple of things. This is not a "fixed" issue as it has been closed as "won't fix" effectively and a workaround has been provided.

The agreed upon solution is one must link to both `libncurses` and `libtinfo` instead of just `libncurses`. To do this, we are supplying a `pkg-config` file that will give the proper linking arguments. As I can't see how you have built `samtools`, I can't comment on whether that is being done correctly or not. So it may not work with this copy of `ncurses`. However, the fact that it is looking for `_stdscr` in `ncursesw` suggests it is not built with this `ncurses`. Feel free to link the recipe/build log of `samtools` if you have it. Also would be happy to discuss this with the maintainers of the `samtools` package.

Just FYI it looks like you are using `conda-build` version `2.0.2`. However, this package is built with `1.x`. So we are not compatible with that version (have a shorter prefix length). Though I don't think this is causing this problem here per se, but it is worth being aware of. We do plan on rebuilding for version `2.0.x` soon.
